### ISSUE TITLE
Error: Got an error from AGPU.

### ISSUE THREAD

**Issue by nolwennfournier** [woden-engine/woden#1]
Hello,

The installation of woden2 seems successful, but when I start a demo (WTFSSampleApplicationCube new openInOSWindow), I have got an error from AGPU : 
```
WTPipelineStateCache >> buildShaderSignature:
signatureBuilder addBindingBankElement: bindingType bindingPointCount: bankElement bindingPoints.
```
```
AGPUShaderSignatureBuilder >> addBindingBankElement: bindingPointCount:
resultValue_ := AGPUCBindings uniqueInstance
addBindingBankElement_shader_signature_builder: (self validHandle) type: type
```
resultValue_ return me -2 as error code.

Computer with Ubuntu 16.10 64 bits, and Radeon R7 360.

Thanks !

**Comment by ronsaldo** [comment]
Can you tell me whether libAgpuVulkan.so (or libAgpuVulkan_d.so) is found
under native-libraries-32/AgpuIcd? There is an obsolete OpenGL backend for
fallback which is untested. I am wondering if all of the dependencies
required for building the Vulkan backend were satisfied or not.

Can you try running the following with an open Transcript?

WTEngine tracingEnabled: true.
WTEngine new inspect

Best regards,
Ronie

2017-03-03 5:08 GMT-03:00 nolwennfournier <notifications@github.com>:

**Comment by nolwennfournier** [comment]
Answer of `locate libAgpuVulkan` : 
```
woden2/build-32/abstract-gpu/dist/AgpuIcd/libAgpuVulkan_d.so
woden2/native-libraries-32/AgpuIcd/libAgpuVulkan_d.so
```

I'm sorry, I forget to tell that during the compilation, there were warning with `OpenGL not found`. 
I found surprising that the compilation ends.

In my terminal, I have the following error : 
```
Required extentions are missing.
Error: Got an error from AGPU.
```

In my transcript, I have just: 
```
...finished baselineGot an error from AGPU: -2
```

Thank you for the quick answer
Nolwenn

**Comment by ronsaldo** [comment]
>
> Required extentions are missing.
>
> const char *requiredExtensionNames[] = {
    VK_KHR_SURFACE_EXTENSION_NAME,
#if defined(_WIN32)
    VK_KHR_WIN32_SURFACE_EXTENSION_NAME,
#elif defined(__unix__)
    VK_KHR_XCB_SURFACE_EXTENSION_NAME
#else
#error unsupported platform
#endif
};

Are you using MIR or Wayland? What is the output of vulkaninfo?


2017-03-03 7:38 GMT-03:00 nolwennfournier <notifications@github.com>:

**Comment by nolwennfournier** [comment]
I have done a standard installation of Ubuntu 16.10 for Woden2. I don't know which one is the default display server.

Vulkaninfo : 
```
Cannot create Vulkan instance.
/build/vulkan-ijAUlz/vulkan-1.0.21.0+dfsg1/demos/vulkaninfo.c:675: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

So, I have tried to install `mesa-vulkan-drivers mesa-vulkan-drivers:i386` and restart the installation.
No difference in woden2.

But, in Vulkaninfo : 
```
/build/vulkan-ijAUlz/vulkan-1.0.21.0+dfsg1/demos/vulkaninfo.c:1415: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by ronsaldo** [comment]
>
> mesa-vulkan-drivers mesa-vulkan-drivers

The version in the official repositories only  have vulkan drivers for the
Intel graphics cards.

For AMD, they are two vulkan drivers, the open source RADV (and
incomplete), and the proprietary AMDGPU Pro driver. For both of these
drivers, I believe that It can be bit tricky installing the vulkan support
because they require enabling experimental support for older graphics cards
(Southern Island, and Sea Island) in the amdgpu kernel driver. There are
instructions about how to install these drivers somewhere on the internet.
The minimal required support is being able to run vulkaninfo. I manage to
install the RADV driver in a old HD 7770, however Woden 2 is hanging the
machine when running the Cube demo, so I do not know whether it is going to
work for you.


2017-03-03 8:18 GMT-03:00 nolwennfournier <notifications@github.com>:
