### ISSUE TITLE
VRDisplay feature is not supported on device ?

### ISSUE THREAD

**Issue by Figgg** [woden-engine/woden#10]
Hello,

When launching any example scene like the pool one using allowingVR, we still get the OSWindow view while we want it to be opened in the headset.

When looking a bit into the code, we can see that the FFI call isFeatureSupportedOnDevice returns false when passed AGPU_FEATURE_VRDISPLAY as a parameter. From there, we cannot see the AGPU library code to know how it decides if VR is supported or not since it's compiled.

We don't know why it thinks VR isn't supported but the headset is plugged in, and SteamVR is working since it's running in the background. We're using a laptop VR ready with an NVidia GeForce GTX 1070 GPU and we're running Debian 9.8.0.

If you need any further information, just ask. Thank you

**Comment by ronsaldo** [comment]
Hello,

You have to enable VR in the Woden settings before : 

![woden-settings](https://user-images.githubusercontent.com/1550655/56365643-5721ee00-61bf-11e9-88cb-b29c973aa7d2.png)

Make sure you have the VR setting enabled, otherwise an AGPU device with VR support will not be requested. You may need to reset the default WDCEngine after enabling that option:

```smalltalk
WDCEngine reset
```

**Comment by Figgg** [comment]
Nice ! It works perfectly, everyone in the office tried it. It freezes a bit sometimes but it's really smooth most of the time. We're going to make good use of it in the following months.
The Vive support has been really quick, and so was your answer, thank you.
